### ISSUE TITLE
Add dynamic showing of remaining stock widget values - name, %increase, price, etc.

### ISSUE THREAD

**Issue by jonagull** [jonagull/bohemian-dash#18]

**Comment by fkallevik** [comment]
- [ ] Get company list (for dropdown) from API instead of hardcoding it.
- [ ] Company name should not be hard coded. Get company details from RapidApi using company symbol (e.g AAPL) instead.
- [ ] Only display data for the last month and maybe 
- [ ] Title/caption the chart according to what is being displayed'
- [ ] Get stock price from API instead of hardcoding it and show relevant currency symbol
- [ ] Make graph fill the width of the widget'
- [ ] Get monthly increase/decrease % and display that in green or red depending on bear/bull trend.
- [ ] Increase contrast for X-axis text

**Comment by jonagull** [comment]
X-axis has been taken out, as now we display the time period over chart and under ticker. The design team has had ideas of creating a custom tooltip, discussion of this is in the works, as it seems some of the documentation has been deprecated and no longer offers support.
